name:            Map Academy
title:            Map Academy
baseurl:        /MapAcademy
tagline:          Learn to make maps online
description:      Everything you needed to know about online mapping in a free and easy to follow online course.
permalink:      classes/:title